version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web
hooks:
  BeforeInstall:
    - location: scripts/clean_public_dir.sh
      timeout: 300
      runas: root
      
  ApplicationStart:
    -location: scripts/start_server.sh
      

